name: deploy code
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: list files
        run: ls -l
      - run: yarn install --frozen-lockfile
